version: 2
updates:
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    reviewers:
      - "ader1990"
    assignees:
      - "ader1990"
    labels:
      - "Type: Dependencies"
      - "Lang: Dockerfile"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "Type: Dependencies"
      - "Type: CI"
