name: Deploy
on:
  workflow_dispatch:

env:
  DOCKER_USERNAME: tiryoh
  DOCKER_IMAGENAME: ubuntu-desktop-lxde-vnc
  GIT_CONFIG_USER: Tiryoh@GitHubActions
  GIT_CONFIG_EMAIL: tiryoh@gmail.com

jobs:
  build-and-deploy:
    runs-on: self-hosted
    strategy:
      matrix:
        distro:
          - jammy

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          submodules: true

      - name: Setup QEMU
        uses: docker/setup-qemu-action@v2

      - name: Setup Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to docker.io
        uses: docker/login-action@v2
        with:
          username: ${{ env.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Prepare Docker metadata
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            ${{ env.DOCKER_USERNAME }}/${{ env.DOCKER_IMAGENAME }}
          tags: |
            type=raw,value=${{ matrix.distro }}
            type=raw,value=${{ matrix.distro }}-{{date 'YYYYMMDDTHHmm'}}
          flavor: |
            latest=${{ matrix.distro == 'jammy' }}
            prefix=
            suffix=

      - name: Build and Publish
        id: docker-build
        uses: docker/build-push-action@v4
        with:
          context: .
          platforms: linux/amd64, linux/arm64
          outputs: type=registry # same as --push, push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}


      - name: Get Current Job Log URL
        id: jobs
        uses: Tiryoh/gha-jobid-action@v0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          job_name: build-and-deploy (${{ matrix.distro }})

      - name: Update wiki
        env:
          DOCKER_TAGNAME: ${{ matrix.distro }}
        run: |
          DOCKER_SNAPSHOT=$(cat << EOF | grep ".*-.*T.*" | sed -E "s/.*:(.*-[0-9]*T[0-9])/\1/g"
          ${{ steps.meta.outputs.tags }}
          EOF)
          echo $DOCKER_SNAPSHOT
          DOCKER_DIGEST=${{ steps.docker-build.outputs.digest }}
          echo $DOCKER_DIGEST
          DOCKER_DIGEST_SHORT=$(echo ${DOCKER_DIGEST} | sed -E 's/.*([0-9a-z]{12})[0-9a-z]{52}$/\1/g')
          echo $DOCKER_DIGEST_SHORT
          DOCKER_SNAPSHOT_IMAGE_HISTORY_URL=$(echo "https://hub.docker.com/r/${DOCKER_USERNAME}/${DOCKER_IMAGENAME}/tags?page=1&name=${DOCKER_SNAPSHOT}")
          git clone --depth=1 https://${GITHUB_ACTOR}:${{ secrets.GITHUB_TOKEN }}@github.com/${GITHUB_REPOSITORY}.wiki.git wiki
          cd wiki
          LINE=$(grep -n "add ${{ matrix.distro }} msg after this line" ${{ matrix.distro }}.md | cut -d ":" -f 1)
          head -n $LINE ${{ matrix.distro }}.md > tmp.md
          echo "* \`${DOCKER_DIGEST_SHORT}\`" | tee -a tmp.md
          echo "    * uploaded on $(date --iso-8601="minutes")" | tee -a tmp.md
          echo "        * ${{ steps.jobs.outputs.html_url }}" | tee -a tmp.md
          echo "    * snapshot" | tee -a tmp.md
          echo "        * [\`${DOCKER_SNAPSHOT}\`](${DOCKER_SNAPSHOT_IMAGE_HISTORY_URL})" | tee -a tmp.md
          tail -n +$(( $LINE+1 )) ${{ matrix.distro }}.md >> tmp.md
          mv tmp.md ${{ matrix.distro }}.md
          git config --local user.email "${GIT_CONFIG_EMAIL}"
          git config --local user.name "${GIT_CONFIG_USER}"
          git add ${{ matrix.distro }}.md
          git commit -m "Update ${{ matrix.distro }}.md"
          git fetch origin && git merge origin/master --no-edit && git push origin master || \
          git fetch origin && git merge origin/master --no-edit && git push origin master
